apiVersion: apps/v1
kind: Deployment
metadata:
  name:  java-deployment
spec:
  selector:
    matchLabels:
      app: java-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app:  java-deployment
    spec:
      containers:
      - name:  java-deployment-container
        image:  mayuriwarudkar/java:j1
        ports:
        - containerPort: 80
